apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: petclinic-external-secret
  namespace: petclinic
  labels:
    app.kubernetes.io/managed-by: terrafrom
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: petclinic-secret-store
    kind: SecretStore
  target:
    name: petclinic-db-secret
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: tf-eks-petclinic-secrets
      property: POSTGRES_USER
  - secretKey: POSTGRES_PASS
    remoteRef:
      key: tf-eks-petclinic-secrets
      property: POSTGRES_PASS
  - secretKey: POSTGRES_URL
    remoteRef:
      key: tf-eks-petclinic-secrets
      property: POSTGRES_URL