apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-svc
  labels:
    app: petclinic
    app.kubernetes.io/instance: petclinic
    app.kubernetes.io/name: petclinic
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "aa60d78897e0a4a3fa2736484c55a526-3012038f3bfec9bb.elb.us-east-1.amazonaws.com"
    http:
      paths:
      - pathType: Prefix
        path: /petclinic
        backend:
          service:
            name: petclinic-svc
            port:
              number: 8080 
  tls:
    - hosts:
      - petclinic.elmesary.net
      secretName: letsencrypt-prod