apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-devops-eks-petclinic-app-external-secrets-sa
  Annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::532323453523:role/tf-devops-eks-petclinic-app-external-secrets-irsa"
automountServiceAccountToken: true